### PR TITLE
FFmpegFrameGrabber's timeout for RTSP #711

### PR DESCRIPTION
**Pull request by d-a-gerashenko**
Two methods to test "connection is lost" situations. In addition to #711 issue.

### CODE REVIEW

**Comment by saudet** [comment]
Thanks for the contribution! Since this works only for RTSP, maybe we could name the sample RtspStreamingTimeout.java, what do you think?

**Comment by d-a-gerashenko** [comment]
Ok. Should I do it or you will rename it?

**Comment by saudet** [comment]
Yes, please rename! Thanks

**Comment by saudet** [comment]
It looks like we can set the "timeout" for the HTTP protocol as well:
http://ffmpeg.org/ffmpeg-all.html#http
Would you mind adding this in commented lines of (even if untested) code?
And then we can name the file, maybe, "FFmpegStreamingTimeout.java"? :)

**Comment by d-a-gerashenko** [comment]
Interesting. Yes, sure) I'll test it. If it works there is no need in "stimeout".

**Comment by d-a-gerashenko** [comment]
Nope. "rw_timeout" isn't working. Actually it's working when grabber is already connected and has lost connection. But it's not working when network interface was disabled before connections attempt.

**Comment by saudet** [comment]
Ok, cool, thanks for testing. Let's just leave that as well as "timeout"
for the other protocols in comment.

**Comment by d-a-gerashenko** [comment]
> continuous-integration/travis-ci/pr — The Travis CI build failed 

Is it normal?

I didn't change the file's name because the option doesn't work the way we expected. Right?

**Comment by saudet** [comment]
Yeah, I still need to get Travis going. You can ignore that for now.

**Comment by saudet** [comment]
I'm sure the "timeout" and "rw_timeout" options work for some protocols...

**Comment by d-a-gerashenko** [comment]
Ok. I can rename it to FFmpegStreamingTimeout but I will add comment that it was tested with RTSP only.

**Comment by saudet** [comment]
Sounds good! Thanks

**Comment by d-a-gerashenko** [comment]
I think it's done.

**Comment by saudet** [comment]
Thanks! Had to fix the filename though

**Comment by d-a-gerashenko** [comment]
Oops. Sorry)

**Pull request merged**
