### PR TITLE
Use Mat and other newer classes

### PR DESCRIPTION
**Pull request by mavriksc**
Shows the source image marked with rectangle the template image and the matching result matrix.

### CODE REVIEW

**Comment by saudet** [comment]
Awesome!  @emanresusername Could you try it out and let me know if that works for you? Thanks!

**Comment by emanresusername** [comment]
so i haven't been running this out of this repo, not sure if that makes a difference, but i'm getting the following, looks like maybe a hardcoded path? `/Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.1.0/modules/imgproc/src/templmatch.cpp`

```text
OpenCV Error: Assertion failed ((depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2) in matchTemplate, file /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.1.0/modules/imgproc/src/templmatch.cpp, line 1062
[error] (run-main-0) java.lang.RuntimeException: /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.1.0/modules/imgproc/src/templmatch.cpp:1062: error: (-215) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function matchTemplate
java.lang.RuntimeException: /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.1.0/modules/imgproc/src/templmatch.cpp:1062: error: (-215) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function matchTemplate

	at org.bytedeco.javacpp.opencv_imgproc.matchTemplate(Native Method)
	at matching.TemplateMatching.newStyle(TemplateMatching.java:46)
	at matching.TemplateMatching.main(TemplateMatching.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```
my project has this `build.sbt`
```scala
name := "test-javacv"
scalaVersion := "2.11.8"

classpathTypes += "maven-plugin"

libraryDependencies += "org.bytedeco" % "javacv" % "1.2"
```
`project/plugins.sbt`
```scala
addSbtPlugin("org.bytedeco" % "sbt-javacv" % "1.10")
```
and i just copied the `samples/TemplateMatching.java` from here into `src/main/java/matching/TemplateMatching.java`

**Comment by mavriksc** [comment]
that path is probably fine i'm not sure why `saudet` is in the path... but it's finding the code but an assertion fails that it runs before executing. i had some issues like that when an image wasn't loaded or was overwritten. debug by printing out the  the depth and dimensions before you call the matching, and see if it is what the function expects. there were also some things while using Mats that was unexpected. if you `zero` it the size goes to 0x0. i ran across these when trying to create masks and filling with ones or zeros had very strange results. plus you lose some info in the debugger directly because there are a lot of pointers.

**Comment by mavriksc** [comment]
this may not help but the pom for where i test my code before putting it in  my project.   
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.mavriksc</groupId>
  <artifactId>matching</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
	   <dependency>
	    <groupId>org.bytedeco</groupId>
	    <artifactId>javacv</artifactId>
	    <version>1.2</version>
	  </dependency>
	 
	  
  </dependencies>
</project>
```

**Comment by emanresusername** [comment]
i've been spoiled by `sbt` gotta get my head back around maven and poms 😅 
so if i clone this repo and use that as the `pom.xml`
then run
`mvn package exec:java -Dexec.mainClass=matching.TemplateMatching /path/to/image /path/to/template`
that should work?

**Comment by mavriksc** [comment]
Everything i see with that error there is a problem with one of the images, this is probably not an dependency issue. [c++](http://stackoverflow.com/questions/31622153/template-matching-a-screenshot-fails-on-assertion) but it's running the same code.  before you run the template matching try and output the mat type for the source and template and make sure they are the same.  i'll try and start a new project paste in the code and see what i get.

**Comment by mavriksc** [comment]
yeah i did goof was loading the template in color. you should be able to match templates in color also but they both have to be color. in your program update line ~44: `Mat template = imread(args[1],CV_LOAD_IMAGE_GRAYSCALE);` this is 0 was 1 sry.

**Comment by emanresusername** [comment]
ok, with that one the error goes away but its back to the old behavior. 
program starts
i see a java process start
then it just hangs

somebody pointed out in the gitter chat that maybe it's just the displaying of images that's off and the underlying computation is still working fine.

is there an example/snippet that i could play with that'd output like a list of (x,y) coordinates where the matches are found and bypass any possible display stuff?

**Comment by mavriksc** [comment]
instead of using the imshow() waitkey and destroy all windows. just print out the max point value. or use something like this. pass in the "results" mat and a value like 0.95-0.99. in my exp you will get clusters instead of single points.
```
public static List<Point> getPointsFromMatAboveThreshold(Mat m, float t){
		List<Point> matches = new ArrayList<Point>();
		FloatIndexer indexer = m.createIndexer();
		for (int y = 0; y < m.rows(); y++) {
        	for (int x = 0; x < m.cols(); x++) {
        		if (indexer.get(y,x)>t) {
					System.out.println("(" + x + "," + y +") = "+ indexer.get(y,x));
					matches.add(new Point(x, y));					
				}
			}			
		}		
		return matches;
	}
```	
I have not used the canvasFrame yet in my stuff but have done some things in Swing so i may be able to update this further but will be some time.

**Comment by emanresusername** [comment]
ok, definitely getting some results coming out of that, don't know enough about this space to give much intelligent insight into the results though, but here are my results

seems to work for something where there's definitely a match:
full
part
```text
(16,48) = 0.9999739
```
but for a template with no match, just prints out coordinates and scores indefinitely:
nope
[output.txt](https://github.com/bytedeco/javacv/files/509938/output.txt)

**Comment by mavriksc** [comment]
a tiny patch of dark blue with low detail is going to match pretty well with a lot of things in that source image.  [take a look here for some basics and not so basics](https://www.youtube.com/playlist?list=PLQVvvaa0QuDdttJXlLtAJxJetJcqmqlQq)   
that is in python yes but the method calls and constants will all be the same. Use Mats intead of the numpy arrays. try some images more in line with what you are trying to do with this .   
 [how i use this and look at utils for some useful things](https://github.com/mavriksc/overcomp/tree/master/src/main/java/com/mavriksc/service)

**Comment by saudet** [comment]
@mavriksc Thanks! Good to merge? Formatting is a bit off with a mix of tabs and spaces, but if you're OK with that, let me know, thanks!

**Comment by mavriksc** [comment]
I'm having a hell of a time getting to a page where i can edit that file again to make it all spaces. let me know what's preferred and when i update this for canvasFrame i'll fix the formatting.

**Comment by saudet** [comment]
You just need to clone your fork and push some more commits.

You can use tabs or spaces, doesn't matter, but not being consistent makes
the code harder to read. Thanks!

**Pull request closed without merging**
