### PR TITLE
Ability to do a direct stream copy of audio and / or video instead of re-encoding

### PR DESCRIPTION
**Pull request by alicanalbayrak**
https://code.google.com/archive/p/javacv/issues/456

### CODE REVIEW

**Comment by saudet** [comment]
Great! That's looking good. :+1: Though, it seems to be duplicating a lot of code. I'm wondering, would it be possible to refactor the existing methods to reuse existing code as much as possible?

**Comment by alicanalbayrak** [comment]
Hi Samuel, I did some refactoring works as you asked. Also I updated [PacketRecorderTest.java](https://github.com/alicanalbayrak/javacv/blob/remux/samples/PacketRecorderTest.java) class to check if my update causes any misbehaviour. 

I tested either sample video and IP camera rtsp stream recording _w and w/out audio_.

As far as ```grabFrame()``` and ```grabPacket()```  methods works well, and not effected. If latest change is not satisfactory, please let me know. (Hence, I may need little guidance from you)

**Comment by saudet** [comment]
Yes, that's better, thanks! The `writePacket()` is nice. We should adjust the error message a bit and specify that it might be either an "audio or video frame" though.

Instead of having a separate `setIfmt_ctx()` method, could we simply have an overloaded `start(AVFormatContext ctx)` method? I think that would look nicer.

I'm wondering, is it recommended to always use `avformat_alloc_output_context2()` instead of `avformat_alloc_output_context()`? If so, we might as well use that, and get rid of `oc = null;`.

For the formatting, could you please replace the tabs with 4 white spaces? And then we can squash all those commits together and should be good to merged. :) Good work!

**Comment by alicanalbayrak** [comment]
I changed ```writePacket()``` little bit to improve readibility of the code, and logged stream type when it failed.

Also ```avformat_alloc_output_context()``` seems enaough and works for both circumstances.

**Comment by saudet** [comment]
Ok, cool, looks good! Could you squash all these commits into one? The easiest way is to `git reset master` your branch, recommit, and `git push --force`, and I'll merge this in. Thanks!

**Comment by alicanalbayrak** [comment]
I guess its ready now.

**Comment by saudet** [comment]
Great! Thank you very much!

**Comment by saudet** [comment]
@alicanalbayrak Thanks again for the contribution, but unfortunately, the functions and fields you used are deprecated and will be gone in the next release of FFmpeg. Could you update your code to use non-deprecated APIs? Thanks!

**Comment by alicanalbayrak** [comment]
Hi @saudet ,
Of course, I can update it in a week or two.

**Pull request merged**
