### PR TITLE
Fix FFmpegFrameGrabber to properly seek/skip the data inside custom InputStream

### PR DESCRIPTION
**Pull request by teerapap**
The code previously did not respect `InputStream.skip()` return value. It leads to wrong seek result because the data might not be skipped to the desired offset.

It also assumed that the maximum input stream size is 1MB which might not be the case for bigger file.  The problem arises when that the data after 1MB offset is read and the mark position is reset. It leads to `InputStream.reset()` not reset to the start of the stream as expected.

This merge requests 
* Respect the InputStream.skip() return value
* Assume the input stream maximum size is at integer maximum.

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! But we shouldn't force users to allocate 4 GB of memory to hold the whole stream. Let's make this configurable, via an optional constructor parameter would be best I believe.

**Comment by teerapap** [comment]
@saudet  Thanks for the fast response. It is my bug that I pre-allocate big size of the buffer of `BufferedInputStream`. I fix it in the latest commit.  

Calling `mark()` with big size does not mean the stream have to allocate the buffer with the same size.  At least `BufferedInputStream` does not do that. It grows its internal buffer as needed. 

I'll add another constructor to set this size then.

**Comment by teerapap** [comment]
@saudet  If I add another constructor with optional `maximumSize` of the `InputStream`. 
What should be the default value?     
* `1024*1024` to be backward compatability.
or
* `Integer.MAX_VALUE-8` to cover bigger files by default and let the user set it to lower size if desired.

**Comment by saudet** [comment]
First, we need to pass it as argument to BufferedInputStream, or it won't
work, so let's add that back.

And we can't have something that allocates 2 GB by default, so let's leave
it 1 MB by default yes.

**Comment by saudet** [comment]
Actually, it looks like you're right. Reading an MP4 file works even without passing the size of the buffer as argument to the BufferedInputStream, interesting. How does that work?

**Comment by saudet** [comment]
It does increase its internal buffer as needed. So, looks good to me as it is now. Thanks for the contribution!

**Comment by teerapap** [comment]
Thanks.

**Pull request merged**
