### PR TITLE
Fixed the problem of accessing the device before it was instanciated.

### PR DESCRIPTION
**Pull request by poqudrof**
There was an issue about choosing which camera to activate. 

Discussion with @mattdibi there: https://github.com/bytedeco/javacv/issues/669 .

### CODE REVIEW

**Comment by mattdibi** [comment]
I tested it with the following code:

```java
RealSenseFrameGrabber.tryLoad();
RealSenseFrameGrabber grabber = RealSenseFrameGrabber.createDefault(0);
grabber.enableDepthStream();
grabber.enableColorStream();
grabber.start();

OpenCVFrameConverter.ToIplImage converterToIpl = new OpenCVFrameConverter.ToIplImage();

CanvasFrame colorFrame = new CanvasFrame("Color Stream",1); 
CanvasFrame depthFrame = new CanvasFrame("Depth Stream",1); 

while(true) {

grabber.grab();

IplImage colorImage = grabber.grabVideo();
IplImage depthImage = grabber.grabDepth();

colorFrame.showImage(converterToIpl.convert(colorImage));
depthFrame.showImage(converterToIpl.convert(depthImage));

}
```

Using the SR300 I got the following error:

```
RealSense devices found: 1
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -37314
	at java.awt.image.ComponentColorModel.getRGBComponent(ComponentColorModel.java:903)
	at java.awt.image.ComponentColorModel.getRed(ComponentColorModel.java:944)
	at java.awt.image.ComponentColorModel.getRGB(ComponentColorModel.java:1135)
	at sun.java2d.loops.OpaqueCopyAnyToArgb.Blit(CustomComponent.java:145)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:560)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:541)
	at sun.java2d.loops.MaskBlit$General.MaskBlit(MaskBlit.java:189)
	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Blit.java:204)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:86)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1030)
	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:196)
	at sun.java2d.SunGraphics2D.copyImage(SunGraphics2D.java:3229)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3270)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3214)
	at org.bytedeco.javacv.CanvasFrame$2.paint(CanvasFrame.java:211)
	at org.bytedeco.javacv.CanvasFrame.showImage(CanvasFrame.java:381)
	at org.bytedeco.javacv.CanvasFrame.showImage(CanvasFrame.java:368)
	at org.bytedeco.javacv.CanvasFrame.showImage(CanvasFrame.java:365)
	at Main.main(Main.java:34)
java.lang.ArrayIndexOutOfBoundsException: -37314
	at java.awt.image.ComponentColorModel.getRGBComponent(ComponentColorModel.java:903)
	at java.awt.image.ComponentColorModel.getRed(ComponentColorModel.java:944)
	at java.awt.image.ComponentColorModel.getRGB(ComponentColorModel.java:1135)
	at sun.java2d.loops.OpaqueCopyAnyToArgb.Blit(CustomComponent.java:145)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:560)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:541)
	at sun.java2d.loops.MaskBlit$General.MaskBlit(MaskBlit.java:189)
	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Blit.java:204)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:86)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1030)
	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:196)
	at sun.java2d.SunGraphics2D.copyImage(SunGraphics2D.java:3229)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3270)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3214)
	at org.bytedeco.javacv.CanvasFrame$2.paint(CanvasFrame.java:211)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:64)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -37314
	at java.awt.image.ComponentColorModel.getRGBComponent(ComponentColorModel.java:903)
	at java.awt.image.ComponentColorModel.getRed(ComponentColorModel.java:944)
	at java.awt.image.ComponentColorModel.getRGB(ComponentColorModel.java:1135)
	at sun.java2d.loops.OpaqueCopyAnyToArgb.Blit(CustomComponent.java:145)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:560)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:541)
	at sun.java2d.loops.MaskBlit$General.MaskBlit(MaskBlit.java:189)
	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Blit.java:204)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:86)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1030)
	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:196)
	at sun.java2d.SunGraphics2D.copyImage(SunGraphics2D.java:3229)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3270)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3214)
	at org.bytedeco.javacv.CanvasFrame$2.paint(CanvasFrame.java:211)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:64)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Fixed with:
```java
...
266    int iplDepth = IPL_DEPTH_16U, channels = 1;
...
```
and deleting the endianness part.
Now it works.

Using the R200 I got the following error:
```
RealSense devices found: 1
java.lang.RuntimeException: uvc subdevice 2 cannot provide 1280x720:RGB8@30Hz COLOR
	at org.bytedeco.javacpp.RealSense$device.start(Native Method)
	at RealSenseFrameGrabber.start(RealSenseFrameGrabber.java:237)
	at Main.main(Main.java:19)
```
this is because as documented [here](https://github.com/IntelRealSense/librealsense/blob/master/doc/supported_video_formats.pdf) the R200 doesn't support that stream format.

**Comment by saudet** [comment]
@mattdibi It looks like the endianness of cameras differ, and @poqudrof didn't find a way to query it, so he provides a `setByteOrder()` method. It should work if you call `setByteOrder(ByteOrder.nativeOrder()`, could you confirm?

@poqudrof Do you know if most RealSense cameras are little endian? Being Intel, I guess it would make most sense. If so, maybe we should put it as default?
BTW, IPL_DEPTH_16S returns a negative number, so to use it in arithmetic, be sure to take the absolute value!

**Comment by mattdibi** [comment]
Just checked. I confirm that with setByteOrder it works but I had to keep the stream in 16 bit unsigned, otherwise I have the usual ArrayIndexOutOfBoundsException.

**Comment by saudet** [comment]
@mattdibi Are you having any issues with the latest changes from @poqudrof ? 

In any case, please let me know if you think this is ready to merge! Thanks

**Comment by mattdibi** [comment]
@saudet I just gave it a try. It works for me.

**Pull request merged**
