### PR TITLE
Create OpenCVOptions

### PR DESCRIPTION
**Pull request by matteoformenti**
Show available settings for OpenCVFrameGrabber.setOption(). Based on https://docs.opencv.org/4.1.0/d4/d15/group__videoio__flags__base.html

### CODE REVIEW

**Comment by saudet** [comment]
What is this for?

**Comment by matteoformenti** [comment]
As per [issue #1269](https://github.com/bytedeco/javacv/issues/1269) I suggest to introduce an OpenCVOption class that contains all option keys and names that opencv explains in their documentation. It's just easier to see names instead of numbers while working with those options

**Comment by saudet** [comment]
They are already all here:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/gen/java/org/bytedeco/opencv/global/opencv_videoio.java

**Comment by matteoformenti** [comment]
My bad, i'm sorry. I've searched for them but with no luck.

**Comment by saudet** [comment]
We could add that link to the Javadoc of `OpenCVFrameGrabber` and `OpenCVFrameRecorder` though. What do you think?

**Comment by matteoformenti** [comment]
Sure, that could work

**Comment by saudet** [comment]
Please do send a pull request for that :) Thanks

**Pull request closed without merging**
