### PR TITLE
Add some overload methods of getXxxMetadata() with charset parameter.

### PR DESCRIPTION
**Pull request by Konyaco**

### CODE REVIEW

**Comment by saudet** [comment]
How about having a property for that like setCharet()/getCharset()?
If we do it this way, it could also work well for FFmpegFrameRecorder.

**Comment by Konyaco** [comment]
> How about having a property for that like setCharet()/getCharset()? If we do it this way, it could also work well for FFmpegFrameRecorder.

I think your solution is better. To be honestly, I haven't study other implementations, is it possible to add them to FrameGrabber/FrameRecorder as general methods?

**Comment by saudet** [comment]
Yes, that's the idea. We add "charaset" fields in the parents, which we can use in the FFmpeg subclasses.

**Comment by Konyaco** [comment]
> Yes, that's the idea. We add "charset" fields in the parents, which we can use in the FFmpeg subclasses.

I tried, and works fine. Should I make a new PR?

**Comment by saudet** [comment]
Great! Please do it in this PR. Thanks

**Comment by Konyaco** [comment]
> Great! Please do it in this PR. Thanks

Uhh.. I am sorry that I don't know how to change the branch of PR, so I made a new PR here https://github.com/bytedeco/javacv/pull/1720

**Pull request closed without merging**
