### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ahsandar**
Added the additional library dependencies required to use JavaCV in a SBT based project

### CODE REVIEW

**Comment by saudet** [comment]
Great! Could add the dependencies for FFmpeg, etc, etc as well? Thanks!

**Comment by jpsacha** [comment]
Platform, like `linux-x86`, can be determined automatically using code shown [here](https://github.com/bytedeco/javacv-examples/blob/c2e24d4068cbdf93396b8afa3e63ee898a46f2df/OpenCV2_Cookbook/build.sbt#L17). Maybe worth creating a simple SBT plugin to avoid cutting and pasting, it is 19 lines :)

**Comment by saudet** [comment]
@jpsacha Instead of that code, do you know if it is possible with sbt to call [`Loader.getPlatform()`](http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Loader.html#getPlatform--) directly as a "maven-plugin"? With Maven, AFAIK, it's not possible, but if we can with sbt, it could help provide a nicer workaround.

**Comment by jpsacha** [comment]
SBT can call anything that can be added to its classpath, so it could be possible to call `Loader.getPlatform()` that way. Not sure if it can access a "maven-plugin", will need to check on that.

**Comment by jpsacha** [comment]
@saudet What exactly javacpp "maven-plugin" do?

**Comment by saudet** [comment]
I'm not sure myself, maybe nothing. sbt seems to treat "jar" artifacts differently from "maven-plugin" ones, unlike Maven itself.

**Comment by jpsacha** [comment]
I modified javacv-examples to use `javacpp` to determine platform in [`build.sbt`](https://github.com/bytedeco/javacv-examples/blob/f89a3aae3c55423bfef1e6fe7047340d1328b1a3/OpenCV2_Cookbook/build.sbt#L10):

```
val platform = org.bytedeco.javacpp.Loader.getPlatform
```

To make it work `javacpp` needs to be added to `build.sbt` classpath. It is done in [`project/plugins.sbt`](https://github.com/bytedeco/javacv-examples/blob/f89a3aae3c55423bfef1e6fe7047340d1328b1a3/OpenCV2_Cookbook/project/plugins.sbt):

```
classpathTypes += "maven-plugin"
libraryDependencies += "org.bytedeco" % "javacpp" % "0.11"
```

**Comment by saudet** [comment]
Great :+1: Thanks! BTW, do you know if it's possible to get the dependencies of JavaCV so we can loop over that and add the platform specific artifacts as dependencies?

**Comment by jpsacha** [comment]
If you just want to add dependency on specific preset libraries you could use in `build.sbt` som ething like this:

``` scala
// Platform classifier for native library dependencies
val platform = org.bytedeco.javacpp.Loader.getPlatform
// Libraries with native dependencies
val bytedecoPresetLibs = Seq(
  // library names and versions
  "opencv" -> "2.4.11-0.11",
  "flycapture" -> "2.7.3.19-0.11"
).flatMap { case (lib, ver) =>
  Seq(
    // Add both: dependency and its native binaries for the current `platform`
    "org.bytedeco.javacpp-presets" % lib % ver,
    "org.bytedeco.javacpp-presets" % lib % ver classifier platform
  )
}

libraryDependencies ++= Seq(
  "org.bytedeco" % "javacpp" % javacppVersion,
  "org.bytedeco" % "javacv" % javacppVersion,
  "org.scala-lang.modules" %% "scala-swing" % "1.0.1",
  "junit" % "junit" % "4.12" % "test",
  "com.novocode" % "junit-interface" % "0.11" % "test"
) ++ bytedecoPresetLibs
```

It is also possible to automatically determine all  "org.bytedeco.javacpp-presets" libraries from "javacv" dependencies and add `platform` classifier to each. I will need to think how to actually do it. Though that will possibly add large amount of unneeded dependencies to the project.

**Comment by saudet** [comment]
Yes, I realize it would add a lot of unneeded dependencies. I am just hoping to have something like that as a sample build file, because we can't do it the Maven way. :) There is no hurry, so take your time! Thanks

**Comment by saudet** [comment]
Hi, any updates on this?

**Comment by ahsandar** [comment]
not yet , haven't had time to work on it yet

**Comment by saudet** [comment]
Closing as this is no longer required with the "platform artifacts". We just need to add a dependency on "javacv-platform" or "opencv-platform", for example, which in turn depend on binaries for all platforms. This works not only with Maven, but with Gradle and sbt as well.

**Pull request closed without merging**
