### PR TITLE
Adds FFmpegFilterFrame sample for Android

### PR DESCRIPTION
**Pull request by pachev**

### CODE REVIEW

**Comment by saudet** [comment]
Great! Though since this is 99% identical to the original RecordActivity sample, could you instead simply modify that sample? Thanks!

**Comment by pachev** [comment]
Ok, will do. I didn't want to edit your original code in case someone didn't want a filter. I'll add a control structure for that. I'll send a pull request in the morning.

**Comment by saudet** [comment]
Awesome! You can also simply update the branch of this pull request

**Comment by pachev** [comment]
Ok, I added it to the original RecordActivity sample. Have a good day 😄 !

**Comment by saudet** [comment]
Looks great! Although it would probably be more efficient to create and start the FFmpegFrameFilter only once, alongside FFmpegFrameRecorder, or is this not working because of some bug in JavaCV?

**Comment by pachev** [comment]
Yes, you're right. It's better to start it once when the recorder starts. The code has been updated. Good catch! I've also tested it on a Nexus 5x but with an RTMP feed instead of saving it to the device.

**Comment by saudet** [comment]
Looks good! Thanks a lot

**Pull request merged**
