### PR TITLE
Add missing functionality to FlyCapture2FrameGrbber

### PR DESCRIPTION
**Pull request by jpsacha**
Add missing functionality to get FlyCapture2FrameGrbber on par with FlyCaptureFrameGrbber.
See also [javacpp-presets PR #400](https://github.com/bytedeco/javacpp-presets/pull/400)

### CODE REVIEW

**Comment by moonryul** [comment]
Hi, Samuel. Thanks for your great project.  I downloaded the source code " procamcalib-1.3-bin.zip (146 MB)" from https://github.com/bytedeco/procamcalib. I build the project using Maven build tool within IntelliJ IDEA 2017.1. After building the project,  when I run the application, I get the following error messages, complaining that jniFlyCapture2.dll  is not found:  C:\Users\moonrjung\.javacpp\cache\flycapture-2.9.3.43-1.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniFlyCapture2.dll: Can't find dependent libraries. But there is such a file in the path (flycapture-2.9.3.43-1.3-windows-x86_64.jar file). What would go wrong? Moon R Jung

**Comment by moonryul** [comment]
Another question. I would like to use a Cannon Camera to grab images, and I obtained EDSDK for the camera. How would I add that camera as another frameGrabber? Moon Jung

**Comment by saudet** [comment]
That error just means you haven't installed the right version of FlyCapture2 on your machine.

To support a new SDK, you'll first need to create new presets:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by moonryul** [comment]
Thanks. About the version of FlyCapture2: The current version is  FlyCapture 2.11.3.121 SDK - Windows (64-bit) — 04/13/2017 - 365.1456MB. Procamcalib supports this version?
Moon

**Comment by saudet** [comment]
It should work if we build from source, but not tested yet... @jpsacha ?

**Comment by moonryul** [comment]
@jpsacha:  I read in  https://github.com/bytedeco/javacpp-presets/tree/master/flycapture 
                            that "This directory contains the JavaCPP Presets module for"  FlyCapture 2.10.3.266.
  So, I guess that that directory should be changed in order for me to rebuild for FlyCapture 2.11.3.121 SDK ?  Moon

**Comment by jpsacha** [comment]
Current FlyCapture preset is for v.2.10.3.266. Interestingly only 2.9 and 2.11 versions are visible on PointGrey website right now. I did not have a chance to test 2.11 yet, maybe in a couple of days.

**Comment by jpsacha** [comment]
I've created a [PR #424](https://github.com/bytedeco/javacpp-presets/pull/424) with updated version number for FlyCapture 2.11.3.121.

**Comment by moonryul** [comment]
Thanks for the update. I have downloaded the current procamcalib-master, and tried to build from the source. I have installed 2.11 version of FlyCapture on my PC to the default folder. But still I get the following message when I run the procamcalib app: ( The build looks for flycapture-2.9.3.43-1.3-windows-x86.jar). What should I do?

"C:\Program Files\Java\jdk1.8.0_131\bin\java" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.2\lib\idea_rt.jar=51938:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar;D:\Users\Moon\Dropbox\GPUProgramming\SAR\procamcalib-master\target\classes;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacv-platform\1.3\javacv-platform-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacv\1.3\javacv-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp\1.3\javacpp-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flycapture\2.9.3.43-1.3\flycapture-2.9.3.43-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\librealsense\1.9.6-1.3\librealsense-1.9.6-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\videoinput\0.200-1.3\videoinput-0.200-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv-platform\3.1.0-1.3\opencv-platform-3.1.0-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-android-arm.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-android-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-linux-armhf.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-linux-ppc64le.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-macosx-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.1.0-1.3\opencv-3.1.0-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg-platform\3.2.1-1.3\ffmpeg-platform-3.2.1-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-android-arm.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-android-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-linux-armhf.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-linux-ppc64le.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-macosx-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flycapture-platform\2.9.3.43-1.3\flycapture-platform-2.9.3.43-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flycapture\2.9.3.43-1.3\flycapture-2.9.3.43-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flycapture\2.9.3.43-1.3\flycapture-2.9.3.43-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flycapture\2.9.3.43-1.3\flycapture-2.9.3.43-1.3-linux-armhf.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flycapture\2.9.3.43-1.3\flycapture-2.9.3.43-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flycapture\2.9.3.43-1.3\flycapture-2.9.3.43-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394-platform\2.2.4-1.3\libdc1394-platform-2.2.4-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3-linux-armhf.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3-linux-ppc64le.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3-macosx-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect-platform\0.5.3-1.3\libfreenect-platform-0.5.3-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3-linux-armhf.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3-linux-ppc64le.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3-macosx-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\librealsense-platform\1.9.6-1.3\librealsense-platform-1.9.6-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\librealsense\1.9.6-1.3\librealsense-1.9.6-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\librealsense\1.9.6-1.3\librealsense-1.9.6-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\videoinput-platform\0.200-1.3\videoinput-platform-0.200-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\videoinput\0.200-1.3\videoinput-0.200-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\videoinput\0.200-1.3\videoinput-0.200-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus-platform\2.3.1-1.3\artoolkitplus-platform-2.3.1-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-android-arm.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-android-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-linux-armhf.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-linux-ppc64le.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-macosx-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark-platform\1.07-1.3\flandmark-platform-1.07-1.3.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-android-arm.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-android-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-linux-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-linux-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-linux-armhf.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-linux-ppc64le.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-macosx-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-windows-x86.jar;C:\Users\moonrjung\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3-windows-x86_64.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\modules\org-netbeans-bootstrap\RELEASE802\org-netbeans-bootstrap-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\modules\org-netbeans-core-startup\RELEASE802\org-netbeans-core-startup-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\modules\org-netbeans-core\RELEASE802\org-netbeans-core-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-netbeans-swing-plaf\RELEASE802\org-netbeans-swing-plaf-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-actions\RELEASE802\org-openide-actions-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-awt\RELEASE802\org-openide-awt-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-dialogs\RELEASE802\org-openide-dialogs-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-explorer\RELEASE802\org-openide-explorer-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-filesystems\RELEASE802\org-openide-filesystems-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-modules\RELEASE802\org-openide-modules-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-nodes\RELEASE802\org-openide-nodes-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-util\RELEASE802\org-openide-util-RELEASE802.jar;C:\Users\moonrjung\.m2\repository\org\netbeans\api\org-openide-util-lookup\RELEASE802\org-openide-util-lookup-RELEASE802.jar" org.bytedeco.procamcalib.MainFrame
org.bytedeco.javacv.FrameGrabber$Exception: Failed to load class org.bytedeco.javacv.FlyCapture2FrameGrabber
	at org.bytedeco.javacv.FlyCapture2FrameGrabber.tryLoad(FlyCapture2FrameGrabber.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.bytedeco.javacv.FrameGrabber.init(FrameGrabber.java:50)
	at org.bytedeco.procamcalib.MainFrame.main(MainFrame.java:1278)
Caused by: java.lang.UnsatisfiedLinkError: no jniFlyCapture2 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:613)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.FlyCapture2.<clinit>(FlyCapture2.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:546)
	at org.bytedeco.javacv.FlyCapture2FrameGrabber.tryLoad(FlyCapture2FrameGrabber.java:116)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\moonrjung\.javacpp\cache\flycapture-2.9.3.43-1.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniFlyCapture2.dll: 지정된 프로시저를 찾을 수 없습니다
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)
	... 14 more

**Comment by saudet** [comment]
@moonryul You could compile from source, but there are SNAPSHOT artifacts available here now:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/flycapture/2.11.3.121-1.3.3-SNAPSHOT/
Rename these JAR files (strip the version) and replace the ones that come with ProCamCalib with those.

**Comment by moonryul** [comment]
Dear Samuel. Thanks for your answer. But I already tried to build procamcalib from source. The error message I reported above was while I was building from source. Perhaps I missed something. I will try again

**Comment by moonryul** [comment]
Dear Samuel, thanks for the replay:

 

I have found the following in the pom.xml in javacv-master which I downloaded from the github. 

 

<dependency><groupId>org.bytedeco.javacpp-presets</groupId><artifactId>flycapture</artifactId><version>2.9.3.43-${javacpp.version}</version></dependency>

​

So the version number of flycapture is not what I want. But how can I modify this pom file? It does not seem to belong to me??

 

Moon R Jung

**Comment by saudet** [comment]
Like I said, if you don't want to build from source, just replace the JAR files instead.

**Comment by moonryul** [comment]
Aha...Hmm.  I think I don't undestand what you mean by "building [procamcalib] from source". When I  copy the current procamcalib-mater to my PC, and build using Intellij IDEA,  the building process show the following message: 
 [INFO] Copying flycapture-2.9.3.43-1.3-linux-x86.jar to D:\Users\Moon\Dropbox\GPUProgramming\SAR\procamcalib-master\procamcalib-master\target\flycapture-linux-x86.jar. 

So, it automatically copies the wrong version of flycapture! What would be wrong with me?
Moon

**Comment by saudet** [comment]
Then add the dependency that you want! If you cannot figure out how to do that though, we can copy the JAR file manually, so please do that instead.

**Comment by moonryul** [comment]
Thanks. I made some progress in building from source. The building process shows the following error message: 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.994 s
[INFO] Finished at: 2017-06-02T10:47:29+09:00
[INFO] Final Memory: 13M/32M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project procamcalib: Could not resolve dependencies for project org.bytedeco:procamcalib:jar:1.3: The following artifacts could not be resolved: org.bytedeco.javacpp-presets:flycapture:jar:2.11.3.121-1.3, org.bytedeco.javacpp-presets:flycapture-platform:jar:2.11.3.121-1.3: Could not find artifact org.bytedeco.javacpp-presets:flycapture:jar:2.11.3.121-1.3 in netbeans (http://bits.netbeans.org/maven2/) . Can I do something about this problem?
Moon R. Jung

**Comment by saudet** [comment]
Yes, you can, like I said just copy the JAR files manually.

**Comment by moonryul** [comment]
Dear Samuel, 

(1)  I tried to build javacpp package from source from after downloading the current javacpp-master for  windows x-86. I used maven tool within Intellij IDEA.  got the following error message:

 It complains:   'stdio.h': No such file or directory. This file is in C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt in my PC. This path is defined in the INCLUDE environment variable. What would be the cause for this error?

Running org.bytedeco.javacpp.PointerTest
Builder
Generating D:\Users\Moon\Downloads\Downloads\javacpp-master\javacpp-master\target\test-classes\org\bytedeco\javacpp\jniPointerTest.cpp
Compiling D:\Users\Moon\Downloads\Downloads\javacpp-master\javacpp-master\target\test-classes\org\bytedeco\javacpp\windows-x86\jniPointerTest.dll
cl "/IC:\Program Files (x86)\Java\jdk1.8.0_131\include" "/IC:\Program Files (x86)\Java\jdk1.8.0_131\include\win32" D:\Users\Moon\Downloads\Downloads\javacpp-master\javacpp-master\target\test-classes\org\bytedeco\javacpp\jniPointerTest.cpp /Oi /O2 /EHsc /Gy /GL /MD /LD /W3 /link /OUT:jniPointerTest.dll psapi.lib 
x86�� Microsoft (R) C/C++ ����ȭ �����Ϸ� ���� 19.00.24215.1
Copyright (c) Microsoft Corporation. All rights reserved.



(2) I also tried to build javacv package from javacv-master. I got the following errors.
What should I do to solve this problem. I really want to build from source. 

Failed to execute goal on project javacv: Could not resolve dependencies for project org.bytedeco:javacv:jar:1.3.3-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:javacpp:jar:1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:opencv:jar:3.2.0-1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:ffmpeg:jar:3.2.4-1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:flycapture:jar:2.11.3.121-1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:libdc1394:jar:2.2.5-1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:libfreenect:jar:0.5.3-1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:libfreenect2:jar:0.2.0-1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:librealsense:jar:1.9.6-1.3.3-SNAPSHOT, org.bytedeco.javacpp-presets:videoinput:jar:0.200-1.3.3-SNAPSHOT,

**Comment by saudet** [comment]
You don't need to build that. If you insist on using Maven, try to read
some documentation, at least.

**Comment by moonryul** [comment]
Hi, Samuel. Can I change the termination criteria for camera-projector calibration in Procamcalib? To get better reprojection errors, I would like to increase the iteration number.
Sincerly Moon R. Jung, Sogang Univ, Seoul, Korea

**Comment by saudet** [comment]
Yes, that's in the settings in the GUI.

**Comment by moonryul** [comment]
default

Here is the screen capture of the setting GUI, but I could not find parameters related to the Termination Criteria.
Moon

**Comment by saudet** [comment]
Those are the termination criteria, what would you like to know?

**Pull request merged**
