### PR TITLE
add a realtimeStreaming example

### PR DESCRIPTION
**Pull request by wangxi761**
#1633 

first , add a realtimeStreaming example than can Simulate the "-re" parameter in ffmpeg

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Could you instead put that directly in `FFmpegFrameGrabber.grab()` with a new flag like `boolean atFrameRate` though?

**Comment by wangxi761** [comment]
@saudet 
sure，Originally planned。
but It takes me some time to finish it ， so I will give an example first

**Comment by saudet** [comment]
Thanks! If you're having problems building JavaCV or something, let me know and I'll help you out.

**Comment by wangxi761** [comment]
```
    public synchronized Frame grabFrame(boolean doAudio, boolean doVideo, boolean doProcessing, boolean keyFrames, boolean doData) 
```
this methond may be a bad design ，As a low-level execution method, it uses the public declare。if we add a param to this ,
Other people's call may be broken. 
do you think so? i would make it private  in other method and Keep its reference
@saudet

**Comment by saudet** [comment]
Just add another overload like was done for doData. :)

**Comment by wangxi761** [comment]
build project with some dependency error
image

**Comment by wangxi761** [comment]
another question , i want to write some unit test in /platform/test
but how can i read file in ci process @saudet

**Comment by saudet** [comment]
> build project with some dependency error

You can ignore that class, it's deprecated.

> another question , i want to write some unit test in /platform/test
> but how can i read file in ci process @saudet

What do you mean? It's just a normal machine, we can read file normally.

**Comment by wangxi761** [comment]
while all test is ok , in my local machine . I don't know if the file for the build machine exists . like such code in  [FrameGrabberTest.java](https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java)
```
        File tempFile = new File(Loader.getTempDir(), "test.mkv");
```
Does it run unit tests when it is built?  If not, I will ignore it

**Comment by wangxi761** [comment]
well ,function has been implemented,we can use it by two way
```
FFmpegFrameGrabber.grabFrame(true,true,true,false,true,true))
```
or
```
FFmpegFrameGrabber.setOption("re","true");
```

**Comment by saudet** [comment]
> while all test is ok , in my local machine . I don't know if the file for the build machine exists . like such code in [FrameGrabberTest.java](https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java)
> 
> ```
>         File tempFile = new File(Loader.getTempDir(), "test.mkv");
> ```
> 
> Does it run unit tests when it is built? If not, I will ignore it

The file will exist if you create it. I still don't understand what you're worried about. Just try it and if it doesn't work, then we can look at the error message.

> FFmpegFrameGrabber.setOption("re","true");

Please don't do that, create a new property like getAtFrameRate() and setAtFrameRate() for that please, and then remove the atFrameRate flag from grab().

**Comment by wangxi761** [comment]
@saudet 
It's done and the local test has passed

**Comment by saudet** [comment]
Since this doesn't depend on FFmpeg and we can use it with others like OpenCVFrameGrabber, how about we move this to the parent class FrameGrabber?

**Comment by wangxi761** [comment]
According to the current FrameGrabber design, it is not easy. Different subclasses like OpenCVFrameGrabber/FFmpegFrameGrabber  directly implement the grab() method.
If the grab() method of the parent class is transformed into a template method pattern, we can implement it in the parent class, but I don't know much about other implementations, do they need such a function?

**Comment by saudet** [comment]
I would just add a grabAtFrameRate() method that calls grab(). What do you
say?

**Comment by wangxi761** [comment]
Do all subclasses need this parameter？ if not

**Comment by saudet** [comment]
I would do this without a new property, just one new method.

**Comment by wangxi761** [comment]
well ,  add a method to FrameGrabber and a unit test FrameGrabberRealTimeTest

**Comment by saudet** [comment]
Looks good, thanks! But the test is failing...

**Comment by wangxi761** [comment]
because i remove the video path and rtmp server path when i commit ，They only exist in my local

**Pull request merged**
