### PR TITLE
Sample FFmpegFrameFilter - yadif deinterlacing

### PR DESCRIPTION
**Pull request by matrupihai**
A sample for FFmpegFrameFilter - the frames are deinterlaced with yadif (the bgr24 format is specified into the ffmpeg filter string)

### CODE REVIEW

**Comment by saudet** [comment]
Sorry, I'm a bit late into checking this, but this is great! Thanks for the contribution

**Comment by matrupihai** [comment]
No problem, I just realised the filter is initialized only when it's null
(so just the first time the method is called) and I wanted to change this.
If you think it's not necessary I can leave it like that.

Thanks,
Mihai

**Comment by saudet** [comment]
Yes, please to make changes. Any modifications you make to your fork's branch will show up here!

**Comment by matrupihai** [comment]
Ok, will do.
Thanks!

**Comment by saudet** [comment]
Let me know when it's good to merge. Thanks!

**Comment by matrupihai** [comment]
Hello,
I think it's ok to merge. Thanks!

**Comment by saudet** [comment]
Great! Thanks for the contribution

**Pull request merged**
