### PR TITLE
Fixed nullPointerException issue and realsense frame data issues

### PR DESCRIPTION
**Pull request by mattdibi**
I had some time and kinda fixed the problem I reported [here](https://github.com/bytedeco/javacv/issues/669).

Here is the sample code I used to test it:

```java
import org.bytedeco.javacv.*;
import org.bytedeco.javacpp.*;

import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;

public class Main {

    public static void main(String[] args) {

        try {
            RealSenseFrameGrabber grabber = RealSenseFrameGrabber.createDefault(0);
            grabber.tryLoad();
            grabber.enableDepthStream();
            grabber.enableColorStream();
            grabber.start();

            OpenCVFrameConverter.ToIplImage converterToIpl = new OpenCVFrameConverter.ToIplImage();

            CanvasFrame colorFrame = new CanvasFrame("Color Stream",1); 
            CanvasFrame depthFrame = new CanvasFrame("Depth Stream",1); 

            while(true) {

                grabber.grab();

                IplImage colorImage = grabber.grabVideo();
                IplImage depthImage = grabber.grabDepth();

                colorFrame.showImage(converterToIpl.convert(colorImage));
                depthFrame.showImage(converterToIpl.convert(depthImage));
                
            }

        } catch (Exception e) {
            System.out.println( e );
        }

        return;
    }

}
```

### CODE REVIEW

**Comment by saudet** [comment]
Great! Thanks a lot. Let's see what the author (@poqudrof) has to say about it.

**Comment by poqudrof** [comment]
Hey, 

I see the issue, here are some explanations: 

(first lines) The ```tryLoad()``` operation is static because the context should be unique. This method assures it. I did not dig much but I tried to create two contexts and it was not pretty. 

Then the device instanciation is ***not*** in the tryload because there could be ***multiple devices***. 
So these parts should remain the same. 

(259) About the depth data, I don't remember if the data is signed or not. The idea is to get 16 in a clean way.

(272) The next part is about endiannes, it is kind of legacy from other FrameGrabber. I don't have different endianness machines so I did not bother. Anyway we can comment it out it that breaks your code, but it might be interesting to find out why. 

(311) Then the last edit about  BGR vs RGB  should be left to user not to the driver level. In your solution you create a new image to convert and return the RGB image. It is quite bad memory wise to create an image at each frame. I suggest to create it first in you main, and then use the `cvCvtColor` after the grab rather than putting it inside the grab. 

To sum up, you can update your main to make static calls like this : 

``` java
           RealSenseFrameGrabber.tryLoad();   // load the context
           // then the camera #0
           RealSenseFrameGrabber grabber = RealSenseFrameGrabber.createDefault(0);
            grabber.enableDepthStream();
            grabber.enableColorStream();
            grabber.start();

...

       int colorWidth = RealSenseFrameGrabber.DEFAULT_COLOR_WIDTH;
       int colorHeight = RealSenseFrameGrabber.DEFAULT_COLOR_HEIGHT;
       IplImage rgbImage = IplImage.create(colorWidth, colorHeight, IPL_DEPTH_8U, 3);
       while(true) {
                grabber.grab();

                IplImage bgrImage = grabber.grabVideo();
                cvCvtColor(bgrImage, grbImage, CV_BGR2RGB);

                IplImage depthImage = grabber.grabDepth();

                colorFrame.showImage(converterToIpl.convert(colorImage));
                depthFrame.showImage(converterToIpl.convert(depthImage));
     }           
...
```

If it works for you update your commit to just update the problems at lines `259` and `272`. 
Cheers, 
Jeremy.

**Comment by mattdibi** [comment]
Thanks for explaining the first part of the code. I may have rushed the modifications for that.
Anyway, as I answered in the [issue](https://github.com/bytedeco/javacv/issues/669), I still can't make your code work.

On a side note: the RealSense cameras output an unsigned 16 bit depth stream as documented [here](https://github.com/IntelRealSense/librealsense/blob/master/doc/projection.md#depth-image-formats). When I tried to change that in your code it gave me a lot of errors on the CanvasFrame... commenting out the endianness part resolved everything. Hence my modifications to that part.

**Comment by mattdibi** [comment]
Closing the pull request because the problem was fixed [here](https://github.com/bytedeco/javacv/pull/677)

**Pull request closed without merging**
