### PR TITLE
Java2DFrameConverter.cloneBufferedImage

### PR DESCRIPTION
**Pull request by d-a-gerashenko**
https://github.com/bytedeco/javacv/issues/736

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! But what is "SignedBufferedImage"? In any case, that should go in the "else" branch only. We need to use the first method when the type is "TYPE_CUSTOM".

**Comment by d-a-gerashenko** [comment]
Is uses SignedBufferedImage to avoid images comparison by data. It contains String sign. It shouldn't be here.
I updated code.

And what would be if we won't use getType() when image type isn't equal to BufferedImage.TYPE_CUSTOM?

	new BufferedImage(
		source.getColorModel(),
		source.copyData(null),
		source.isAlphaPremultiplied(),
		null
	);

**Comment by saudet** [comment]
We need to call getType().

**Comment by saudet** [comment]
BTW, this doesn't build. Please make the build pass.

**Comment by d-a-gerashenko** [comment]
Oh, Travis works now, that's good.

**Comment by saudet** [comment]
Looks good! Thanks

**Pull request merged**
