### PR TITLE
Refs #357: Upgrade to VideoCapture API

### PR DESCRIPTION
**Pull request by lloydmeta**
## Summary
As requested, this is my attempt at upgrading `OpenCVFrameGrabber` to use the new VideoCapture C++ API. A few caveats:

- ~~I couldn't test this at all; can't figure out how to get the dependencies to download. The IDE is happy with me adding Sonatype snapshots as a new repository, but `mvn` gave me the `Failed to execute goal on project javacv: Could not resolve dependencies for project org.bytedeco:javacv:jar:1.2-SNAPSHOT...`~~ I tested by using older non-snapshot dependencies and a very basic this with a very basic webcam to `CanvasFrame` program
- I'm not sure if this will actually help with @PhilAndrew 's problem on Windows10.

## Changes
- Upgrade OpenCVFrameGrabber to use the new C++ VideoCapture API
- ~~Add a mention for SBT-OpenCV~~

### CODE REVIEW

**Comment by lloydmeta** [comment]
Link to #357

**Comment by saudet** [comment]
Thanks! Looks good. It's possible to test this by yourself as a modification of JavaCV 1.1. The API of OpenCV hasn't changed between these versions. Could you try it out?

**Comment by lloydmeta** [comment]
For what it's worth, I changed the dependencies to JavaCV 1.1, and a few other dependencies until the project would build and ran the following:

```java

import org.bytedeco.javacv.CanvasFrame;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber;
import org.bytedeco.javacv.OpenCVFrameGrabber;


public class Demo {
    public static void main(String[] args) {
        //Create canvas frame for displaying webcam.
        CanvasFrame canvas = new CanvasFrame("Webcam");

        //Set Canvas frame to close on exit
        canvas.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

        //Declare FrameGrabber to import output from webcam
        FrameGrabber grabber = new OpenCVFrameGrabber(0);


        try {

            //Start grabber to capture video
            grabber.start();

            //Declare img as Frame
            Frame img;

            while (true) {

                //inser grabed video fram to Frame img
                img = grabber.grab();

                //Set canvas size as per dimentions of video frame.
                canvas.setCanvasSize(grabber.getImageWidth(), grabber.getImageHeight());

                if (img != null) {
                    //Show video frame in canvas
                    canvas.showImage(img);
                }
            }
        }
        catch (Exception e) {
        }
    }
}
```

And it gave me a CanvasFrame showing my own ugly mug, which I guess is good.

**Comment by saudet** [comment]
Yeah, it looks good, thanks! Could you just remove the bit about SBT-OpenCV though? Because actually, I was thinking of moving your sbt-javacpp and sbt-opencv repositories to https://github.com/bytedeco/ and give you full access to them obviously. How does that sound? Also, I think sbt-javacv would be a more accurate name. OpenCV comes with an unrelated set of wrappers, so it would be less confusing saying that you're using the ones used by JavaCV. :)

**Comment by lloydmeta** [comment]
Given that [bytedeco.org](http://bytedeco.org/about/) strongly represents you as an individual only, I would rather keep my plugins in my own namespace for now.

**Comment by saudet** [comment]
It does? That's not my intention though. How could we change that? Oh maybe I could start by adding the names of everyone to the about page, even if they don't write anything about themselves... ?

**Comment by saudet** [comment]
In any case, could we make this pull request only about the fix/enhancement to OpenCVFrameGrabber? I'd merge this in right away :)

**Comment by lloydmeta** [comment]
I think it depends on what you want bytedeco.org to be. If you want it to be something that represents you as an individual (which I totally respect), then keep it as is. But if you want it to be an organisation+namespace where core related projects could be absorbed, then, based on organisations like [ScalaNLP](http://www.scalanlp.org/people/), and [Typelevel](http://typelevel.org/about.html), I might suggest the following:

- Make the About page be a short, point-form list of goals of the Bytedeco family of software
- Add a People page to allow contributors to write a short blurb (maybe 200 words or less), have a link to their Twitter/homepage and maybe a photo/avatar. You don't need to write things for other people, just let people know how they can be added and the conditions for being added (e.g. their project was absorbed into the organisation)

**Comment by lloydmeta** [comment]
> In any case, could we make this pull request only about the fix/enhancement to OpenCVFrameGrabber? I'd merge this in right away :)

Sure sounds good; regarding the other discussion, you can message me [on Twitter](https://twitter.com/meta_Lloyd)

**Comment by lloydmeta** [comment]
Ok, done; link has been removed. Any idea when the next release will be?

**Comment by saudet** [comment]
Right, let me reorganize the About page a bit here then and I'll ask for everyone's impression including yours then :) Thanks for the feedback and the pull requests!!

**Comment by saudet** [comment]
BTW, for consistency, we should probably do the same thing in `OpenCVFrameRecorder` and switch to the `VideoWriter` API...

**Comment by saudet** [comment]
So, er, would you like to work on that? Would be great :)

**Comment by lloydmeta** [comment]
Hey, somewhat swamped at the moment, but I did get to take a look. One thing that stood out to me was that it seems with `VideoWriter`, you no longer get to specify Codec and PixelFormat separately: instead it takes what is called a FourCC ??

I'm not familiar enough with media-stuff to really know what all that stuff means :D

**Comment by saudet** [comment]
No hurry, just wanted to be clear :) Thanks for your interest.

The C API doesn't do codecs or pixel format either. It only takes a FourCC too. So it should be pretty straightforward to move that one to the C++ API as well.

**Comment by lloydmeta** [comment]
When it instantiates the C VideoWriter, it [looks like it passes them](https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/OpenCVFrameRecorder.java#L81) on the JavaCV side, but you're right, according to the [OpenCV API](http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videowriter-videowriter), it doesn't.

**Pull request merged**
