### PR TITLE
Split stereo or merge monos helper

### PR DESCRIPTION
**Pull request by steeveen**
#2036

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Please fix it so it compiles when built from the command line with `mvn clean compile`:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/saudet/projects/bytedeco/javacv/samples/SplitMerge.java:[35,8] class AduioSplitMergeHelper is public, should be declared in a file named AduioSplitMergeHelper.java
[ERROR] /home/saudet/projects/bytedeco/javacv/samples/SplitMerge.java:[1,27] package lombok.extern.slf4j does not exist
[ERROR] /home/saudet/projects/bytedeco/javacv/samples/SplitMerge.java:[3,17] package org.junit does not exist
[ERROR] /home/saudet/projects/bytedeco/javacv/samples/SplitMerge.java:[34,2] cannot find symbol
  symbol: class Slf4j
[INFO] 4 errors 
```

**Comment by steeveen** [comment]
Sorry. I forget remove the test tag. I have fixed it.

**Comment by steeveen** [comment]
Ok, I have commited all the change

**Review by saudet — APPROVED** [review]
Looks good! Thanks for the contribution

**Pull request merged**
