### PR TITLE
Support change of resolution during grabbing. Usecase: UDP streaming …

### PR DESCRIPTION
**Pull request by mifritscher**
…with changing sources / qualities.

Test included.

Signed-off-by: Michael Fritscher <michael.fritscher@telematik-zentrum.de>

### CODE REVIEW

**Comment by saudet** [comment]
Looks good, but for some reason, your tests are not getting run by Maven. Could you check out why this is the case? The same is happening with pull #770. Thanks!

**Comment by mifritscher** [comment]
I think this is because I didn't registered them. I'll need to search the relevant file first ;-)

**Comment by saudet** [comment]
No, JUnit should pick them up automatically...

**Comment by saudet** [comment]
Looks like we have an answer here:
https://stackoverflow.com/a/6178629
Any reason to not just put them in FrameGrabberTest?

**Comment by mifritscher** [comment]
Aaaahhhhh - naming conventions :-) Thanks for this hint!

I can put the test into the already existing FrameGrabberTest file, no problem. I only thought that you prefer to put it into an extra file ;-)

**Comment by saudet** [comment]
Yes, FrameGrabberTest is fine, as long as they pass :)

**Comment by mifritscher** [comment]
Ok, seems to work now :-) I had to leave the test in an extra file - I have the feeling that else  FrameGrabberTest would be overhelmed by this test (3 helper functions, 2 threads, 3 global variables)

**Comment by saudet** [comment]
Sure, that's fine, thanks! We just need to remove FFmpegFrameLock.java now :)

**Pull request merged**
