### PR TITLE
exposing the file with api preference constructor of VideoCapture

### PR DESCRIPTION
**Pull request by kwatters**
This is a pull request that exposes the VideoCapture constructor that includes the apiPreference.  I think this is what Spawn32 is looking for in https://github.com/bytedeco/javacv/issues/1021

### CODE REVIEW

**Comment by saudet** [comment]
Looks good, let's do the same for the other constructors!

**Comment by kwatters** [comment]
I assume you're referring to all of the following:

      VideoCapture capture = new VideoCapture();
      VideoCapture capture = new VideoCapture(BytePointer filename);
      VideoCapture capture = new VideoCapture(int index);
      VideoCapture capture = new VideoCapture(long size);
      VideoCapture capture = new VideoCapture(Pointer p);
      VideoCapture capture = new VideoCapture(String filename);
      VideoCapture capture = new VideoCapture(BytePointer filename, int apiPreference);
      VideoCapture capture = new VideoCapture(String filename, int apiPreference);

I could work some logic into handle each of those case if you want.  I don't know if there's much benefit to the new VideoCapture(); constructor.  This is probably a slightly larger refactor...

**Comment by saudet** [comment]
No, I mean `OpenCVFrameGrabber`'s constructors. We only really need `File` and `deviceNumber`.

**Comment by saudet** [comment]
Or maybe just `File`, it doesn't support `apiPreference` for `deviceNumer`?

**Comment by kwatters** [comment]
I'm pretty sure file & device number are mutually exclusive.  I added a constructor that allows file + api preference.

**Pull request merged**
