### PR TITLE
OpenCV structure (de)serialization

### PR DESCRIPTION
**Pull request by Maurice-Betzel**
Added memory and file based OpenCV structure (de)serialization sample

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! You're demonstrating for AKAZE though, so a better name might be
OpenCVAkazeSerialization, what do you think?

**Comment by Maurice-Betzel** [comment]
AKAZE is just the content producer, if you really want, i will rename it. The principals stay the same.

**Comment by saudet** [comment]
Yes, the principal is the same, but you're actually using AKAZE in there. People understand this is just sample code, and will copy/paste what they need. Using a generic name for a class that is not could cause confusion...

**Comment by saudet** [comment]
Maybe OpenCVFeatures2dSerialization would be an even better name though?

**Comment by Maurice-Betzel** [comment]
Squash and merge

**Pull request merged**
