### PR TITLE
Update Frame

### PR DESCRIPTION
**Pull request by dragos-d**
This is the pull request as Samuel requested. I added the clone() method and I also added a long timeStamp for future implementation, because I think it's better that the frame itself contains the time signature when it was shot rather than reading the grabber's timestamp.

P.S. cc950be is up to date. I messed up some things because I'm trying to learn how to use pull requests :)))

### CODE REVIEW

**Comment by saudet** [comment]
Could you remove all the tabs and replace them with 4 white spaces each? Also "timestamp" is one word, so do not capitalize it. I'll merge once this is fixed, thank you for your contribution!

**Comment by dragos-d** [comment]
8f08cc4 is up to date. I hope I didn't miss any tab. I also replaced divisions in cloneBufferArray() with bit operations (shift right). It should work faster.

**Comment by saudet** [comment]
Thanks! (And no, using shift instead of division doesn't make it faster, it just make it harder to read.)

Now, could you please squash all your changes into one commit, as shown for example on this page:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

And I'll merge that! Thanks

**Comment by dragos-d** [comment]
Well... I tried and I tried and I eventually messed up the things. I keep getting the error for the latest update:
fatal: reference is not a tree 8f08cc4c645c8fc5530b3eb9043793a80a661fa6
I really don't know what else to do. I think I keep getting this error because I didn't commit the updates in my repository, but here.

**Comment by saudet** [comment]
It might be easier to reset your branch, recommit, and force push:
http://stackoverflow.com/a/8991659/523744
That's pretty straightforward.

**Comment by saudet** [comment]
Please recreate your branch if you still intend to merge this in eventually, thank you.

**Comment by dragos-d** [comment]
I think I squashed them into one single update: 9e707b6d873eeaf53a30806c1da3bdc5e5ec39e9
I don't know if this is what you want. Please let me know.

**Comment by saudet** [comment]
You've restored your branch, that's good, but the commit above isn't part of your branch. You could try to reset you branch to master (`git reset --hard master` should do it) and commit only once all your changes to your branch (`dragos-d:dragos-d-patch-1-2`), and then `git push --force` to upload it here.

**Comment by dragos-d** [comment]
What about this: https://github.com/dragos-d/javacv/commit/9e707b6d873eeaf53a30806c1da3bdc5e5ec39e9

**Comment by dragos-d** [comment]
Oh... I noticed that the last updates were squashed in the wrong branch (master). I'll try to move the last update to dragos-d-patch-1-2. I have no idea how this works, but I'd like to learn how to do it.

**Comment by dragos-d** [comment]
Now I think it's ok. Please let me know if I did it right. Thank you!

**Comment by saudet** [comment]
Yes, it's alright. The commit message is a bit weird, but no matter, thanks for the contribution! :+1:

**Comment by dragos-d** [comment]
Thank you too for your patience and for the hints on git!

**Pull request merged**
