### PR TITLE
Issue 1161

### PR DESCRIPTION
**Pull request by k3rnL**
[https://github.com/bytedeco/javacv/issues/1161](https://github.com/bytedeco/javacv/issues/1161)

### CODE REVIEW

**Comment by saudet** [comment]
This isn't going to work when `Frame.opaque` isn't a `Pointer`...

**Comment by saudet** [comment]
I'm pretty sure all that we need to do is just removing the calls to `position(int)` and using other methods to get and set the values.

**Comment by k3rnL** [comment]
It's what I did on FrameConverter, for FrameRecorder.. Yes I used pointer from opaque, I didn't know that opaque can be another things than Pointer

**Comment by k3rnL** [comment]
Now the pointer is created on the buffer instead of opaque.

**Comment by saudet** [comment]
Right, but it was *already* doing that before. Unless there is a good reason to change the method signature of `recordImage()`, could you change it back to what it was before? Also, please do not revert the changes from the master branch.

**Comment by k3rnL** [comment]
It's my point of view, but recordImage deal only with pointer, what's the sense to give it Buffer in this case ?
That's why I changed it.

Next, there is difference between before and my changes, the old code was changing the position and create a pointer on the buffer returned by position(), what lead in concurrency issue. My changes creates a new pointer on the buffer and change the position of the created pointer.
Before: new BytePointer(new Pointer(image[0].position(0)));
Now: new BytePointer(new Pointer(frame.image[0])).position(0);

**Comment by saudet** [comment]
No, `recordImage()` doesn't need a `Pointer`, it works with any `Buffer`, try it.

Like I said, we just need to change it so that it doesn't need to call `position()`. As you point out, we should be able to make it work fine that way.

**Comment by k3rnL** [comment]
Yes it works with any buffer because it's converted in pointer inside of the method. av_image_fill_arrays require bytepointer or bytebuffer. But anyway, I don't care it will work as same for me. 

I did the change, let me know if it's ok for you ;)

**Comment by saudet** [comment]
Yes, this is starting to look good, thanks! But please rebase your branch on master or apply the changes somehow.

**Comment by saudet** [comment]
Reopened as pull #1166.

**Pull request closed without merging**
