### PR TITLE
[fix] filter: add args modify

### PR DESCRIPTION
**Pull request by fastZhe**
Recently, I created an overlay filter and found that the size of each input and pixelFormat cannot be customized, resulting in incorrect output video. Therefore, I added the following code, which can be modified after the original configuration is generated.

### CODE REVIEW

**Comment by saudet** [comment]
Ah, I see, you need to set different inputs/outputs differently. What about making imageWidth, imageHeight, and pixelFormat into array properties instead?

**Comment by fastZhe** [comment]
Yes, I need to add a foreground image to the background video, but I found that the size of the foreground image is the same as the original video when outputting it.


> outputs

**Comment by fastZhe** [comment]
> Ah, I see, you need to set different inputs/outputs differently. What about making imageWidth, imageHeight, and pixelFormat into array properties instead?

I didn't quite understand, do you mean you need to replace the current object array with a pojo array? Or do you need to modify the imageWidth, imageHeight, and pixelFormat properties in the filter to array?

**Comment by saudet** [comment]
I was thinking of modifying existing properties, but this gets ugly. I think we could simply add a couple of new properties to FrameFilter.java like:
```java
String[] videoFilterArgs = null;
String[] audioFilterArgs = null;
```
I don't think we need callbacks?

**Comment by fastZhe** [comment]
> I was thinking of modifying existing properties, but this gets ugly. I think we could simply add a couple of new properties to FrameFilter.java like:
> 
> ```java
> String[] videoFilterArgs = null;
> String[] audioFilterArgs = null;
> ```
> 
> I don't think we need callbacks?

Okay, I got it. Before starting, if these two parameters are set, all input arg strings for video or audio are allowed to be customized by the user. Otherwise, the previous template will be used for filling. Do I understand correctly? If there is no problem, I will modify it according to this.

**Comment by fastZhe** [comment]
@saudet Thanks for the suggestion. I have already pushed a version and implemented it using properties.Please help me take a look, thank you.

**Comment by saudet** [comment]
Thanks! That looks alright, but is it OK for your needs?

**Comment by fastZhe** [comment]
> Thanks! That looks alright, but is it OK for your needs?

Yes, it meets my needs very well.

**Review by saudet — APPROVED** [review]

**Pull request merged**
