### PR TITLE
fix #645 SeekableOutputStream

### LINKED ISSUE #645: FFmpegFrameRecorder didn't work with OutputStream in Android
In my Android test application FFmpegFrameRecorder work properly when i pass File in conctructor, but when i pass OutputStream, app crashes and in Logcat i can see only `com.github.crazyorr.ffmpegrecorder A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 29234 (Thread-266)`
Code, where i init my frame recorder: 
`String recordedTime = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());`
`File file = CameraHelper.getOutputMediaFile(recordedTime, CameraHelper.MEDIA_TYPE_VIDEO);`
`FileOutputStream fos = new FileOutputStream(file);`
`mFrameRecorder = new FFmpegFrameRecorder(fos, videoWidth, videoHeight, 1);`
`mFrameRecorder.setFormat("mp4");`
`mFrameRecorder.setSampleRate(sampleAudioRateInHz);`
`mFrameRecorder.setFrameRate(frameRate);`
`mFrameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);`
`mFrameRecorder.setVideoOption("crf", "28");`
`mFrameRecorder.setVideoOption("preset", "superfast");`
`mFrameRecorder.setVideoOption("tune", "zerolatency");`
Gradle:
```
compile(group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.2') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3', classifier: 'android-arm'
```
Before that i use FFmpegFrameRecorder via just passing file in constructor, but in my app i need possibility to write video from camera using OutputStream.
Please help, maybe i understand something wrong

### PR DESCRIPTION
**Pull request by svorlauf**
Added a SeekCallback and SeekableOutputStream interface to write e.g. mp4 files into a byte array
As requested in issue #645

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Let's also add a small unit test for this to make sure it works.

**Comment by saudet** [comment]
Also, can we make this work with any `ByteArrayOutputStream`? It looks like we can do this by moving all logic out from `SeekableOutputStream` into `SeekCallback`, but am I missing something that prevents us from doing that?

**Comment by svorlauf** [comment]
The problem `ByteArrayOutputStream` is that the byte array is not public but protected. So it either has to be extended or accessed by reflections. I also like to have an interface to maybe change the implementation without needing to add it to javacv first

**Comment by svorlauf** [comment]
I am not sure about unit tests for video creation are there any examples? Or are you talking about the ´SeekableByteArrayOutputStream´ only?

**Comment by saudet** [comment]
> The problem `ByteArrayOutputStream` is that the byte array is not public but protected. So it either has to be extended or accessed by reflections. I also like to have an interface to maybe change the implementation without needing to add it to javacv first

You're right, it's probably not worth hacking this too much. Let's put the interface outside as a top-level class as well. And to make it more consistent with conventions, let's name the method `seek(...)`.

> I am not sure about unit tests for video creation are there any examples? Or are you talking about the ´SeekableByteArrayOutputStream´ only?

Yes, just something to test `SeekableByteArrayOutputStream` and make sure it produces the expected array with a few typical calls.

**Comment by svorlauf** [comment]
>Let's put the interface outside as a top-level class as well. And to make it more consistent with conventions, let's name the method seek(...).
done

I added some test cases for write and seek. There is also added on test to compare .mp4 written to file and `SeekableOutputStream` but i do not know wether it might fail depending on the environment if the encoder is not deterministic. If so we will have to remove the test

**Comment by svorlauf** [comment]
I tried to follow code conventions. If there is anything amiss just give some hints (e.g. missing documentation)

**Comment by svorlauf** [comment]
By the way. I am new to GitHub. Ist there besides the issues and pull requests any forum for general questions? E.g. code style, Java compatibility version etc

**Comment by saudet** [comment]
> I tried to follow code conventions. If there is anything amiss just give some hints (e.g. missing documentation)

I try to follow the conventions from the original document here:
https://www.oracle.com/technetwork/java/codeconvtoc-136057.html 
And when there isn't any contradictions, the ones from here as well:
https://google.github.io/styleguide/javaguide.html
But there is a lot that isn't documented either, so I just go with what makes most sense and what I see others do. Rereading those documents again though, there is a lot I'm not doing like they are doing, so maybe I'll change a few things... (There's also a lot of Javadoc missing. I could use some help with that, for example, see issue #1356.)

> By the way. I am new to GitHub. Ist there besides the issues and pull requests any forum for general questions? E.g. code style, Java compatibility version etc

As mentioned in the README.md file, there is a mailing list here:
- https://groups.google.com/forum/#!forum/javacv

But because accessing Google from China and a few other countries isn't reliable, many people just post their questions as GitHub issues. There isn't anything else than that.

**Pull request merged**
